### ISSUE TITLE
Blank files after creating an archive then opening a file

### ISSUE THREAD

**Issue by NhgrtPlayer** [EternalYoshi/ThreeWorkTool#3]
Steps to reproduce the bug :

- Create an archive
- Open a file (I'm using mnchscmn.arc)
- Every file is here, but they are blank 
![image](https://user-images.githubusercontent.com/16834449/177426115-9dc04551-38f7-4841-8233-4debe828ee1a.png)

**Comment by EternalYoshi** [comment]
Wish I saw this sooner, but I got this fixed. Next big release will have the fix.
